controller_list:
  - name: widowx_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - widowx_joint_1
      - widowx_joint_2
      - widowx_joint_3
      - widowx_joint_4
