controller_list:
  - name: fake_widowx_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
initial:  # Define initial robot poses per group
  - group: widowx_arm
    pose: home